name: "Format"
on:
  push:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn run format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: Apply eslint fix"
