name: "Version"

on:
  push:
    branches:
      - master

jobs:
  version:
    name: "Generate a new version"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: "Setup node"
        with:
          node-version: 15.x

      - name: "Install dependencies"
        run: yarn install

      - name: "Generate new release version"
        run: yarn run release

      - name: "Push new version"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
